[package]
#name = "ecdsa_lib"
name = "digsig"
version = "0.1.0"
edition = "2021"

[dependencies]
k256 = { version = "0.13", features = ["ecdsa", "pem"] }
rand_core = { version = "0.6", features = ["std"] }
ecdsa = "0.16"
